server:
  port: 9090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: system
    url: jdbc:oracle:thin:@localhost:1521/ORCL
    username: System
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
