server:
  port: 3333
spring:
  application:
    name: API-GATEWAY
zuul:
  prefix: /ms
  routes:
    greet:
      path: /api2/**
      serviceId: GREET-SERVICE
    welcome:
      path: /api1/**
      serviceId: WELCOME-SERVICE